# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install Node 24
        uses: actions/setup-node@v7
        with:
          node-version: '24'
      
      - name: Install dependencies
        run: npm install

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build Wasm Package
        run: |
          cd projects/flow-path
          npm run build-wasm
        
      - name: Build Flow Path Demo
        run: npm run build-flow-path-demo

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/flow-path-demo/browser

  deployment:
  
    environment:
        name: github-pages
        url: ${{steps.deployment.outputs.page_url}}

    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
      
    steps:          
      - name: Debug environment
        run: |
          echo "GITHUB_RUN_ID: ${{ github.run_id }}"
          echo "GITHUB_WORKFLOW_ID: ${{ github.workflow_id }}"
          echo "GITHUB_RUN_NUMBER: ${{ github.run_number }}"
          env | grep -i github | sort

      - name: Deployment to Github Pages
        id: deployment
        uses: actions/deploy-pages@v3
        
